@startuml
class User{
    -id (PK)
    -username
    -fullName
    -password
    -role
}

enum Role {
    ADMIN
    CUSTOMER

}
class UserProduto{

   - IDUser (FK for User)
   - IDProduct (FK for Product)
   - Date
   - Quantity

}


class Product {
   -id (PK)
   -categoriaID (FK)
   -name
   -price
   -description
   -categoria
}




class Category {
    - id (PK)
    - name
}

class Invoice {
  - id (PK)
  - IDUser (FK)
  - Date
  - TotalValue (total value of the products prices)
  - PayMethod (ex: "MB Way", "Card", "Money")
  - State(ex: "Paid", "Pending", "Canceled")

}

class ProductInvoice {
 - id (PK)
 - IDInvoice (FK)
 - IDProduct (FK)
 - Quantity

}


User "*" --> "1" Role
User "1" --> "*" Invoice
User "1" --> "*" UserProduto
User "1" --> "*" ProductInvoice

UserProduto "*" --> "1" Product

Product "*" --> "1" Category



ProductInvoice "*" --> "1" Product
ProductInvoice "*" --> "1" Invoice
@enduml