spring:
  application:
    name: Produtos API
  datasource:
    url: jdbc:h2:mem:cars
    username: rui
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
